### ISSUE TITLE
Crash with optifine

### ISSUE THREAD

**Issue by Bewmandboom** [alcatrazEscapee/primal-winter#10]
My game seems to crash when i try to run the mod (primalwinter-forge-1.16.2-2.0.0.jar) along side optifine for minecraft 1.16.3. When i run either of them separately they work fine. 

Crash report (first time using pastebin so i assume this is how its done)

https://pastebin.pl/view/4b49871d

**Comment by alcatrazEscapee** [comment]
I can't support using optifine since they're closed source and so I have no idea what manner of thing they're doing here, as the crash report is making a big pile of no sense whatsoever.

*However*, I have been waiting for Forge to implement a proper biome modification API (of which I believe they've recently done), in order to do away with `GrossBiomeHacks` since it's... well... gross. So until such a point at which I can refactor that away, there's not a lot I can do to diagnose or resolve the issue unfortunately.

**Comment by Bewmandboom** [comment]
ok thank you for looking and the quick response.
