### ISSUE TITLE
I slept and the storm ceased

### ISSUE THREAD

**Issue by PastelQueimado** [alcatrazEscapee/primal-winter#109]
I am playing on the 1.20.1 version. I had slept 4-5 times before the storm simply stoped completely. I have been playing for about 4 hours (sleeping every time night comes) and the storm didn't came back.
I had to resort to try and cheat it back but it the /weather is disabled so... i don't know what to do now, kinda relied on it for my modpack to have fun.
Sorry for my bad english, not my first language.
Anyways, if you are reading just wanted you to know that you mod is great! if there is anything i can do to help let me know.

**Comment by alcatrazEscapee** [comment]
The storm is set by `/gamerule doWeatherCycle false` and `/weather thunder` upon initial world creation. I cannot reproduce sleeping causing the weather to switch to non-winter, in vanilla if the game rule above is `false` then weather won't be cleared by sleeping. The `/weather` command is able to be re-enabled in the config if necessary. Otherwise this sounds like you may have a mod conflict or mistakenly changed the game rule as I cannot reproduce any issues in vanilla.

**Comment by PastelQueimado** [comment]
Probably a mod conflict then, thank you for your time!

**Comment by Mdbgamer** [comment]
Sorry to reopen this, but for future note/possible fixes it seems to be a conflict with the SleepWarp and similar mods possibly. I'd have to test it on a separate pack, but I had the same issue. It's strange though, cuz I'd switched another similar mod out for SleepWarp and never had that issue.

**Comment by Mdbgamer** [comment]
Okay, did the test and can confirm, SleepWarp is definitely (one of?) the mods that does that. Which is still wierd, cuz I was using Sleep Overhaul 2 before and _that_ mod didn't do that...
