### ISSUE TITLE
Animals Spawning? Basic Survival Needs?

### ISSUE THREAD

**Issue by ShinSpin** [alcatrazEscapee/primal-winter#114]
Is there anyway that you can config for animals to spawn or to have that feature? Searched everywhere and can't find anything in the folders to make animals spawn. I understand that it's a winter storm but just wanna know. Thanks, and also, your discord invite link has expired.

**Comment by ShinSpin** [comment]
Also I'm aware that Abandoned Villages are the only sources of food, and you'd have to get lucky to even get 1 animal :V

**Comment by alcatrazEscapee** [comment]
Animal spawning is naturally very rare due to snow layering preventing it in most locations (which can be disabled if desired). This is an intentional side effect, as it is possible to get animals to spawn by creating spawn locations for them.

> Also I'm aware that Abandoned Villages are the only sources of food

No, they aren't. In my own playtesting, Kelp, fish, rotten flesh, apples are all fairly easily accessible, zombies will drop potatoes and carrots meaning this mod - while it makes many things _more difficult_ to obtain - I don't believe it makes anything impossible to obtain.

This is generally working as intended.

**Comment by ShinSpin** [comment]
Understandable. I forgot about those features that you listed. So don't worry, I'll still use the mod for my modpack no matter what. Thanks for replying.
