### ISSUE TITLE
Fog disappears when standing on a snow block with layers=8

### ISSUE THREAD

**Issue by fishcute** [alcatrazEscapee/primal-winter#14]
If you stack up snow layers to make it a full block and stand on it, the fog disappears suddenly. 

What I mean by a full block: (The one in the center)
![2020-10-17_05 04 39](https://user-images.githubusercontent.com/47741160/96333175-537e5a00-1036-11eb-9540-0359bf0122ef.png)

When standing on a full block of snow
![2020-10-17_04 57 49](https://user-images.githubusercontent.com/47741160/96333096-f5ea0d80-1035-11eb-96e4-40d16e33bdd4.png)
When standing not on a full block of snow
![2020-10-17_04 58 05](https://user-images.githubusercontent.com/47741160/96333110-07331a00-1036-11eb-947a-81c51310dfd6.png)

EDIT:
Mod version: 1.1.1
Forge

**Comment by RandomMcSomethin** [comment]
Can confirm this happens in the 1.16.3 build, too.

**Comment by alcatrazEscapee** [comment]
How odd. At a wild guess, I'd assume there's something with how snow layers actually have a smaller hitbox than what is rendered (similar to soul sand in 1.16). Otherwise I'm not sure why it would be happening specifically with `snow[layers=8]`

**Comment by fishcute** [comment]
I can try to do some testing and see if it happens on blocks similar to the hitbox that the layer 8 snow block has, not unless you already tested that

**Comment by alcatrazEscapee** [comment]
Alright, so I've identified the problem:

- When the player is standing on a full snow layer (or soul sand), their position is *actually* reported as on the block below - due to the fact these blocks have a less than full hitbox.
- Both of these blocks *also* block light, and namely, getting the light level inside these blocks is reported as 0.
- Primal Winter uses sky light level to reduce the fog effect when you're indoors. This is intentional as otherwise caves and other structures would look very odd with a white fog effect.

Luckily, I should be able to fix this by checking the light level at the player's eye height, not the feet position.

**Comment by fishcute** [comment]
It works, nice!
