### ISSUE TITLE
[Question] How to implement the "escape the snow" scenario?

### ISSUE THREAD

**Issue by tprk77** [alcatrazEscapee/primal-winter#19]
Mentioned in #7 was an idea of escaping the snowy dimension, using a biome whitelist.

> I'd be very curious to see if this concept gets used by packs, and how it does end up. For example, using the biome whitelist, this could be used to create snowy "dimensions" and could very simply be used to "escape" the snowy dimension for something else.

I would really like to set up something like this, and I'm wondering if you could suggest how this might be best accomplished. I'm guessing it would require a mod to add something like a second overworld at least. Do you know if such a mod already exists and could be configured for this purpose? Or would a new mod need to be written?

**Comment by alcatrazEscapee** [comment]
So, the big benefit of using >1.16 for this is you, as a pack maker, can add your own custom dimensions, biomes, etc. all via data packs! See [Custom Worlds](https://minecraft.gamepedia.com/Custom) and [Custom World Generation](https://minecraft.gamepedia.com/Custom_world_generation).

Asides from that, the obvious alternatives would be to use the nether, end, or any modded dimension specifically as a the next stage in a progression pack. i.e. make it quite difficult to get to the nether, but it's required in order to escape the endless snow. Or maybe you need to escape to the betweenlands. Or something else - as long as it doesn't use the overworld biomes.

If you want to chat some more about this idea some more or have other questions, I now have a [discord server](https://discord.gg/EWx23XqsRq) for my mods.

**Comment by tprk77** [comment]
I've been playing around with custom world generation, with the goal of creating a "normal overworld" with `nonWinterBiomes`, and a "snow overworld" with the leftover biomes.

But I've kind of hit a snag, because if the biome source type is [`vanilla_layered`](https://minecraft.gamepedia.com/Custom#Generator_types) (the overworld default), you can't actually customize the list of biomes. If you use `multi_noise`, you can customize the biomes, but it doesn't resemble the usual overworld.

(See also: https://feedback.minecraft.net/hc/en-us/community/posts/360071479691-Biome-list-support-for-vanilla-layered-biome-type-generation-worlds-)

I'm not sure if this is possible, but I think it would be really useful to allow/deny on dimension IDs. It would allow for two improvements:
1. You would not need to "split" the two overworlds by dimensions. You could use the same dimensions in both.
2. You could use the default `vanilla_layered` biome source (instead of `multi_noise`).

Do you think this might be a feature you are willing to add?

**Comment by alcatrazEscapee** [comment]
No, that is not possible. Everything this mod changes is part of the biome data. Biomes have no concept of what dimension they're in. This would never work (consider the following: two players area online, one in the overworld and one in the overworld two, in the same biome, but it needs to be a completely different biome at the same time, when there's only a single instance of that biome in the registry).

**Comment by tprk77** [comment]
Ah, that's kind of too bad, but I understand the limitation and why it's impossible. Thanks for your help!
