### ISSUE TITLE
[Suggestion] Snowy Trees

### ISSUE THREAD

**Issue by NotoriusQ** [alcatrazEscapee/primal-winter#21]
It would be great if Trees that grow in snowy biomes are their Snowy Variants!
Same saplings, but just checks to see whether it's biome is snowy or not, right?

**Comment by alcatrazEscapee** [comment]
So, for a number of reasons, I'm not going to do this.

Basically, in order to properly replace tree placement I have two options:

1. Only replace vanilla trees, by manually re-implenting each and every tree feature to use snowy blocks.
  - This is something I don't even do right now - the snowy trees you see in primal winter were done using a cheeky hack, which replaces the blocks while the chunk is generating, and importantly *only* during chunks present in world generation.
  - This is *much* more reliable than trying to modify the vanilla tree features, especially once you factor in modded trees which could be using vanilla leaves.
  - So, not feasible, due to the possible downsides and the maintenance effort of replacing all vanilla tree generation.
2. Use the same hack I do for world gen, but for all worlds.
  - This is a non-zero performance cost, and a very invasive hack if I extend it past just world gen chunks, to all chunks.
  - This wouldn't just replace trees - it would replace *every* block. Even if the user placed it by hand, or placed it outside of a snowy biome. This is quite clearly not viable, as if I wanted to do that, I would've registry-replaced the vanilla blocks themselves.

In addition to the technical reasons, I don't think this is particularly a good idea. Trees don't grow snowy, they get snowy by the accumulation of snow on top of them. Which is something I think I could do, although it would be less comprehensive, by exploiting the same way snow currently grows. But not simply replacing the trees themselves. To that effect I've opened #42, which is likely where I would take this feature.
