### ISSUE TITLE
When placing a block on snow, snow layers should disappear

### ISSUE THREAD

**Issue by gospodin55** [alcatrazEscapee/primal-winter#3]
When snow is laying on the ground and you place a block its like flying over the snow

**Comment by alcatrazEscapee** [comment]
This is vanilla behavior, why would you expect this to be changed?

**Comment by gospodin55** [comment]
The mod is about winter unlike vanilla, where snow biomes are one of others and it would be a nice feature to see in mod

**Comment by alcatrazEscapee** [comment]
I don't really want to do this as it's a very specific change from vanilla It is a change (and inconsistency) from vanilla. This behavior (replacing instead of placing on top) only applies to things that do not collide. Stacked snow layers can be almost a full block and as such it would be quite weird to replace them.

I also don't see the specific reason. Yes this mod is about turning the entire world into winter, but it does not touch snow placement at all. It sounds like a very random thing to try and modify.
