### ISSUE TITLE
[Suggestion] Separate Dimension

### ISSUE THREAD

**Issue by AmyMialee** [alcatrazEscapee/primal-winter#32]
I love the concept of this mod but I definitely would be much more interested if it was a separate dimension.
I think a clone of the overworld (with the same seed) would make for a quite interesting experience, opening a portal and it being in the same location but a freezing nightmare.
Especially if it worked with Immersive Portals.

**Comment by Snorps** [comment]
Better yet I would love it if there was a config option to choose which dimensions the mod affects yourself.

**Comment by AmyMialee** [comment]
Yea, that'd be great for stuff like twilight forest or other custom overworldy dimensions.
Even the end, I imagine that'd be surreal to see.

**Comment by alcatrazEscapee** [comment]
You can already choose which biomes the mod affects. For twilight forest, or the end, since they both consist of a self contained set of biomes, this is already possible.

As for adding an option to only affect specific dimensions - this is not possible. The biome cannot exist in a different state in two dimensions (i.e., if `minecraft:plains` was normal in the overworld and not in the "snowy dimension"). Indeed, this then becomes a duplication task - instead of `minecraft:plains` in the overworld, we have `primalwinter:plains` in the "snowy dimension". Which brings to mind a couple of things:

- This is already possible with a [datapack](https://minecraft.fandom.com/wiki/Custom_world_generation), you can add new biomes yourself, and select them to or not to be modified by Primal Winter.
- Duplicating the entire overworld is both a whole pile of effort, and way outside the scope of this mod.

So I'll reiterate:

> Yea, that'd be great for stuff like twilight forest or other custom overworldy dimensions.
> Even the end, I imagine that'd be surreal to see.

Everything you just mentioned is already possible, provided you whitelist specific *biomes* to be snowy or not.

And as an aside,

> I think a clone of the overworld (with the same seed) would make for a quite interesting experience, opening a portal and it being in the same location but a freezing nightmare.

This would not, even if it were simple and possible, be the way this mod works. This is not a mod that adds a neat new snowy dimension - this makes *everything* a primordial apocalyptic winter, by design. To that extent, I am not going to add much new "content" to this mod outside of that required to fill in the atmosphere and environment that I'm trying to create (*and also because I seem to have very little time to work on this mod at the moment*)

**Comment by Snorps** [comment]
Oh I assumed stuff like the new sounds and visual changes were just tied to the overworld. Cool ^^
