### ISSUE TITLE
Animals do not spawn on grassblocks if it is the new version

### ISSUE THREAD

**Issue by River25** [alcatrazEscapee/primal-winter#6]
Animals will not spawn on white grass no matter if the layers of snow are removed. (This may not be a bug) Animals will not spawn on regular grass as well.

**Comment by alcatrazEscapee** [comment]
Minecraft version?
Forge or Fabric?
Mod version?

**Comment by River25** [comment]
Minecraft Version: 1.16.1
Fabric Version: 0.8.9
Mod Version primalwinter-fabric-1.16.1-1.0.0.jar

**Comment by alcatrazEscapee** [comment]
I have been unable to reproduce this. Animal spawning seems to work fine on snowy grass, provided there's not motion-blocking levels of snow layers (which I do believe will prevent spawning).

Whether this is something that got inadvertently fixed during the current 1.16.2 update or not, I can't say, but it will likely be fixed in the 1.16.2 release if it's not already.

**Comment by alcatrazEscapee** [comment]
Should be resolved one way or the other by https://github.com/alcatrazEscapee/primal-winter/releases/tag/v1.1.0-fabric
