### ISSUE TITLE
[bug][1.16.5] Crash with Rubidium/Magnesium about mixin

### ISSUE THREAD

**Issue by KuroPeach** [alcatrazEscapee/primal-winter#64]
Crash with Rubidium/Magnesium about mixin. 
![image](https://user-images.githubusercontent.com/19620848/201372261-b4a5c105-6383-4ce0-b26e-4e085fd378c8.png)
When I comment out the client mixin of this mod, I can open the client and enter the world normally.
![image](https://user-images.githubusercontent.com/19620848/201372432-5ba3c33e-3fe7-4a4f-86c7-c148e0c25b77.png)
![image](https://user-images.githubusercontent.com/19620848/201372513-6be22a24-9bdc-47e8-a992-98561681e039.png)
![image](https://user-images.githubusercontent.com/19620848/201372560-42fa01ef-ce3c-421d-afe7-3d61a1ab0632.png)

**Comment by alcatrazEscapee** [comment]
Primal Winter uses this mixin in order to render things like snow particles, rain and wind sounds, etc. Disabling it is the cudgel which will break half the functionality of the mod but yes, make it work. In addition I am no longer supporting 1.16 and do not believe this issue exists in the latest edition of the mod. If it does I may look into it.
