### ISSUE TITLE
Crash on world load with optifine

### ISSUE THREAD

**Issue by Not1anted** [alcatrazEscapee/primal-winter#79]
As the title says.. and when I am loading the world it takes so long too for some reason... I am only using optifine with primal winter :/
this is what the crash says: "The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 7."
I am on the last version 1.20.1 .

**Comment by TenableRelic90** [comment]
Same issue. 1.19.2. Tested with only optifine and Primal Winter mod. No other mods included nor shaders active. Same exact crash report with no other context or information. 

Conclusion: The mod is completely incompatible with optifine. Works perfectly without it. This is not a good look for this mod as it doesn't say it isn't compatible, and therefor most people who try and use this mod are surely going to have issues with no understanding on why.

**Comment by Nugget1321** [comment]
yeah same here is there a way that i can fix it?

**Comment by TenableRelic90** [comment]
> yeah same here is there a way that i can fix it?

Not from what I remember, I ended up not using that mod despite how much I wanted it for my modpack, but I'd say try using the "Oculus" mod instead. It lets you use iris shaders on forge and even gives better performance. I haven't tried that though so you might still run into an error or two but that's the only thing I can think of that would work.

Since its a different shader engine, I doubt the error will pop up, or at least the same one as before. Hope this helps!
